### ISSUE TITLE
how does the operator doc get included

### ISSUE THREAD

**Issue by pwright** [Apicurio/apicurio-docs-playbook#6]
I can see the operator doc is available on website [1], but I cannot see a reference to it on the master branch of this repo..

UPDATE:  I can see reference to operator doc in https://github.com/Apicurio/apicurio-docs-playbook/blob/1.3.x/registry-docs-playbook.yml

So maybe the question is whether the playbook on master needs to be updated?
(asking as I am testing adding search to docs)

[1] https://www.apicur.io/registry/docs/apicurio-registry-operator/0.0.5-dev/index.html
[2] https://github.com/search?l=YAML&q=org%3AApicurio+apicurio-registry-operator&type=Code

**Comment by EricWittmann** [comment]
Hey @pwright - very sorry for the delay in responding to this.  We've been heads down trying to get a bunch of things finished up.  Not a good excuse though.

I think the short answer is that yes, the `master` branch needs to be updated to include the operator docs reference.  The `master` branch of this repository should result in documentation for version 2.0.0 of the registry (and its operator), which is of course the `master` branch of the apicurio-registry and apicurio-registry-operator repositories.

**Comment by pwright** [comment]
thanks @EricWittmann
